name: local
variables:
  - name: baseUrl
    value: http://localhost:8080
  - name: grpcUrl
    value: localhost:50051
  - name: grpcToken
    value: test123
  - name: fabricId
    value: DevNet_VxLAN_Fabric
  - name: switchId
    value: site1-leaf1
  - name: nodeId
    value: ""
  - name: slurmJobId
    value: "12345"
